# For more info on HTTP files go to https://aka.ms/vs/httpfile
@CommandNexus.ApiHostAddress = http://localhost:8080
# GET ALL PLATFORMS
GET {{CommandNexus.ApiHostAddress}}/api/platform

###
# GET PLATFORM BY ID

GET {{CommandNexus.ApiHostAddress}}/api/platform/815ce32b-2128-4857-9579-4ad3d57cb561
Content-Type: application/json


###
POST {{CommandNexus.ApiHostAddress}}/api/platform
Content-Type: application/json

{
  "name": "ASP.NET Core",
  "publisher" : "Microsoft",
  "cost" : "Open Source"
}
