apiVersion:  apps/v1
kind: Deployment
metadata:
  name: platforms-depl  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-nexus-platform-service
  template:
    metadata:
      labels:
        app: command-nexus-platform-service
    spec:
      containers:
        - name: command-nexus-platform-service
          image: natsu2597/commandnexus-platform:latest
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: command-nexus-platform-service
  ports:
  - name: command-nexus-platform-service
    protocol: TCP
    port: 8080
    targetPort: 8080
